version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 882e4559af101c9bb42fdba22f494e398f00dd293242978e8f97aea7fbf20ce4
    docker:
      - image: circleci/node:carbon
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: opeoluwaiyi-kuyoro
          POSTGRES_DB: portfolio-test
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests and post coverage to cc
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --exit-code $?

      # Build the app
      - run:
          name: Build the app
          command:
            npm run build
